### ISSUE TITLE
Sigma js

### ISSUE THREAD

**Issue by 5up3rD4n1** [DUXEL/Dashboard#8]
Make some test to know how to use this framework

http://sigmajs.org/

**Comment by iamdeit** [comment]
In the examples folder of sigmajs.zip, we found the js code for density, centrality and network. We need to find an appropriate graph representation for distance.

**Comment by 5up3rD4n1** [comment]
If the graphs are already seleceted please close this issue.

**Comment by iamdeit** [comment]
We will use only d3 js.
